### PR TITLE
Trying to resolve an issue with using this template with JDK11 and 13

### PR DESCRIPTION
**Pull request by adityai**
I use this template quite often and recently, when I switched to JDK11, I observed that the compilation itself is failing with a javax.xml.bind.JAXBException. I switched back to JDK8 to continue with my work, but I'd like to resolve this JAXBException issue on JDK11 and 13. 

Apparently, some JAVA EE libraries have been removed from JDK9+ and javax.xml.bind is one of them. I haven't been able to resolve the issue yet, even though there are many suggestions on stackoverflow regarding the same problem. None of those suggested solutions worked for me. 

I created Dockerfiles for each JDK. That way, whenever we have a potential fix, we can test on 3 JDKs at the same time by running the build as individual docker image builds. 

I added brief details in the README.md as well. Please help me fix this issue.

### CODE REVIEW

**Comment by Ardesco** [comment]
So is the plan for these docker file to turn them into part of the build process?

**Comment by adityai** [comment]
If this was a real test suite, the Dockerfile can be used to run the test suite, provided it is run in headless mode. By adding this to the project, we are giving users an additional option to use Docker image builds to run their test suites. The user may choose to save the image and re-use it for subsequent test executions. At the same time, for the owner and contributors it is a quick way of testing the template. I set up automatic builds on Docker hub for this project from my fork. In essence, the template is now publicly available as a Docker image for anyone to pull and re-use.

**Comment by adityai** [comment]
I didn’t get a chance to figure out that issue with JDK 13. I am not too concerned about the Dockerfiles. I am interested in resolving the issue with failures when jdk 13 is used.

**Comment by Ardesco** [comment]
I've updated the dependencies to the latest version (and the chrome driver binaries that are pulled down to the latest version). and it seems to be running fine using 

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N/A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
```

Can you see if you are getting any errors with the latest updates.

**Comment by adityai** [comment]
Yes it worked. Thank you. I realized that I don't have the right stuff in the docker containers to actually run the test suites in it. I will update the Dockerfiles and submit another PR, assuming you are ok with adding Dockerfiles to the project.

**Pull request closed without merging**
