### PR TITLE
supports remote selenium-standalone

### PR DESCRIPTION
**Pull request by xywang68**
Hi, @Ardesco , I made some update to the DriverFactory.java, now it supports remote selenium-standalone.

### CODE REVIEW

**Comment by Ardesco** [comment]
This is already supported, you just use the following command:

`mvn clean verify -Dremote=true -DseleniumGridURL=http://{username}:{accessKey}@ondemand.saucelabs.com:80/wd/hub -Dbrowser=firefox`

See the code here:

https://github.com/Ardesco/Selenium-Maven-Template/blob/master/src/test/java/com/lazerycode/selenium/config/DriverFactory.java#L80

**Comment by Ardesco** [comment]
Actually, you are right, I broke it...

**Comment by Ardesco** [comment]
Fixed in a slightly different way, we already have a known DriverType object we can use rather than adding in another case statement.

**Comment by xywang68** [comment]
Hi, @Ardesco , thanks for your respond.
In this case I am trying to test against a remote PC running selenium-standalone. I used the below command line.
mvn verify -Dremote=true -DseleniumGridURL=http://remote.selenium.standalone.ip:port/wd/hub -Dplatform=windows -Dbrowser=ie -DbrowserVersion=11 -X

With your latest code it looks like the test is still trying to find selenium and the IE-driver locally. Am I missing anything? 

Here is a section of the log:

Current Operating System: LINUX
Current Architecture: amd64
Current Browser Selection: ie

Unable to capture screenshot...
org.openqa.selenium.WebDriverException: The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't create a new driver instance for Capabilities [{browserName=ie, version=11, platform=WINDOWS}]

On the other hand with the switch statement that I proposed the remote selenium part is working as expected.

**Comment by Ardesco** [comment]
Ah good old IE, I keep missing IE annoyances due to being a Mac user.

**Comment by Ardesco** [comment]
That should fix it for you, it now returns `internet explorer` instead of `ie`

**Pull request closed without merging**
