### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by paulvi**
just `target`

otherwise did not work.

### CODE REVIEW

**Comment by Ardesco** [comment]
What IDE are you using, the exclusion works fine in my IDE

**Comment by paulvi** [comment]
STS (Eclipse-based) is mine. So it is likely so in any Eclipse

**Comment by Ardesco** [comment]
I use IntelliJ IDEA and the current .gitignore works fine for me, so I've added it in as an addition rather than as a replacement.

**Comment by paulvi** [comment]
great

**Pull request closed without merging**
